name: Autonomous Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-gates:
    name: Validate Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --run

      - name: Build for production
        run: npm run build

      - name: Upload production build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy-staging:
    name: Deploy to Staging
    needs: quality-gates
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Sync build to Cloud Storage
        run: |
          gsutil -m rsync -r dist gs://${{ secrets.GCP_STAGING_BUCKET }}

  deploy-production:
    name: Deploy to Production
    needs: quality-gates
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.preview_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Sync build to Cloud Storage
        id: deploy
        run: |
          gsutil -m rsync -r dist gs://${{ secrets.GCP_PRODUCTION_BUCKET }}
          echo "preview_url=https://storage.googleapis.com/${{ secrets.GCP_PRODUCTION_BUCKET }}/index.html" >> $GITHUB_OUTPUT
