name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: vercel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --run

      - name: Ensure Vite Gemini key fallback
        if: env.VITE_GEMINI_API_KEY == '' && env.GEMINI_API_KEY != ''
        run: echo "VITE_GEMINI_API_KEY=${GEMINI_API_KEY}" >> $GITHUB_ENV

      - name: Build application
        run: npm run build

      - name: Pull Vercel environment information
        run: npx vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        id: vercel
        uses: vercel/action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: ${{ github.ref == 'refs/heads/main' }}
          prebuilt: true
